from gql import Client, gql
from gql.transport.aiohttp import AIOHTTPTransport
import os
import sys
import requests

transport = AIOHTTPTransport(url="https://leetcode.com/graphql/")
client = Client(transport=transport)

if len(sys.argv) < 2:
  print("Question slug is required")
  sys.exit(1)

parsedSlug = sys.argv[1]

def downloadSolution(slug: str):
  if os.path.exists(f'./problems/{parsedSlug}/solution_{parsedSlug.replace("-", "_")}.py'):
    print(f'Question {parsedSlug} already exists')
    return

  query = gql(
      """
      query ($titleSlug: String!) {
        question(titleSlug: $titleSlug) {
            questionId
            questionFrontendId
            boundTopicId
            title
            titleSlug
            content
            translatedTitle
            translatedContent
            isPaidOnly
            difficulty
            likes
            dislikes
            isLiked
            similarQuestions
            exampleTestcases
            contributors {
                username
                profileUrl
                avatarUrl
            }
            topicTags {
                name
                slug
                translatedName
            }
            companyTagStats
            codeSnippets {
                lang
                langSlug
                code
            }
            stats
            hints
            solution {
                id
                canSeeDetail
                paidOnly
                hasVideoSolution
                paidOnlyVideo
            }
            status
            sampleTestCase
            metaData
            judgerAvailable
            judgeType
            mysqlSchemas
            enableRunCode
            enableTestMode
            enableDebugger
            envInfo
            libraryUrl
            adminUrl
            challengeQuestion {
                id
                date
                incompleteChallengeCount
                streakCount
                type
            }
            note
        }
    }
  """
  )
  query.variable_values = { "titleSlug": parsedSlug }

  result = client.execute(query)

  question = result['question']

  slug = question['titleSlug']

  os.makedirs(f'./problems/{slug}', exist_ok=True)

  # Solution

  solution = f"""
# AUTOGENERATED WITH https://github.com/tsecret/leetcode

# URL: https://leetcode.com/problems/{slug}
# topics: {', '.join([tag['slug'] for tag in question['topicTags']])}


"""

  for codeSample in question['codeSnippets']:
    if codeSample['langSlug'] == 'python3':
      with open(f'./problems/{slug}/solution_{slug.replace("-", "_")}.py', "w") as f:
        if "List" in codeSample['code']:
          solution += 'from typing import List\n\n'
        f.write(solution + codeSample['code'])
      break

  print(f"Created solution file for {slug}")

def downloadTestCases(slug: str):
  data = requests.get(f"https://datasets-server.huggingface.co/filter?dataset=newfacade/LeetCodeDataset&config=default&split=train&where=%22task_id%22%20%3D%20'{slug}'&length=10").json()
  question = data['rows'][0]['row']
  tests = 'import unittest\n'
  tests += f'from solution_{slug.replace("-", "_")} import Solution\n\n'
  tests += f'fn = {question['entry_point']}\n\n'
  tests += 'class Test(unittest.TestCase):\n'

  for i, case in enumerate(question['input_output']):
    tests += f"""
    def test_{i}(self):
        self.assertEqual(fn({case['input']}), {case['output']})
    """

  with open(f'./problems/{slug}/test_{slug.replace("-", "_")}.py', "w") as f:
    f.write(tests)

  print(f"Created test files for {slug}")

def main():
  downloadSolution(parsedSlug)
  downloadTestCases(parsedSlug)

if __name__ == '__main__':
  main()
