from typing import List

# AUTOGENERATED WITH https://github.com/tsecret/leetcode

# URL: https://leetcode.com/problems/contains-duplicate
# topics: array, hash-table, sorting


class Solution:
    def containsDuplicate(self, nums: List[int]) -> bool:
      d = {}

      for n in nums:
         if n in d:
            return True
         d[n] = 1

      return False
