
# AUTOGENERATED WITH https://github.com/tsecret/leetcode

# URL: https://leetcode.com/problems/find-the-difference
# topics: hash-table, string, bit-manipulation, sorting

from collections import defaultdict

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        d = defaultdict(int)

        for char in s:
            d[char] += 1

        for char in t:
            d[char] -= 1

        for k, v in d.items():
            if v != 0:
                return k
