
# AUTOGENERATED WITH https://github.com/tsecret/leetcode

# URL: https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string
# topics: two-pointers, string, string-matching


class Solution:
    def strStr(self, haystack: str, needle: str) -> int:
        if len(needle) == 0:
           return 0

        if len(needle) > len(haystack):
           return -1

        l = 0

        while l < len(haystack):

          for r in range(len(needle)):
            if l+r >= len(haystack) or haystack[l+r] != needle[r]:
               break

            if r == len(needle)-1:
               return l

          l += 1

        return -1
