
# AUTOGENERATED WITH https://github.com/tsecret/leetcode

# URL: https://leetcode.com/problems/design-hashmap
# topics: array, hash-table, linked-list, design, hash-function


class MyHashMap:

    def __init__(self):
      self.d = {}

    def put(self, key: int, value: int) -> None:
      self.d[key] = value

    def get(self, key: int) -> int:
      if key in self.d:
        return self.d[key]

      return -1

    def remove(self, key: int) -> None:
      del self.d[key]


# Your MyHashMap object will be instantiated and called as such:
# obj = MyHashMap()
# obj.put(key,value)
# param_2 = obj.get(key)
# obj.remove(key)
