
# AUTOGENERATED WITH https://github.com/tsecret/leetcode

# URL: https://leetcode.com/problems/maximum-number-of-balloons
# topics: hash-table, string, counting

from collections import defaultdict

class Solution:
    def maxNumberOfBalloons(self, text: str) -> int:
        d = defaultdict(int)

        for char in text:
          if char in 'balon':
            d[char] += 1


        return min(d['b'], d['a'], d['l'] // 2, d['o'] // 2, d['n'])
