
# AUTOGENERATED WITH https://github.com/tsecret/leetcode

# URL: https://leetcode.com/problems/valid-anagram
# topics: hash-table, string, sorting


class Solution:
    def isAnagram(self, s: str, t: str) -> bool:
        if len(s) != len(t):
          return False

        d = {}

        for char in s:
            if char not in d:
                d[char] = 0

            d[char] += 1

        for char in t:
            if char not in d:
                return False

            if d[char] == 0:
                return False

            d[char] -= 1

        return True
