
# AUTOGENERATED WITH https://github.com/tsecret/leetcode

# URL: https://leetcode.com/problems/number-of-good-pairs
# topics: array, hash-table, math, counting


from typing import List
from collections import defaultdict

class Solution:
    def numIdenticalPairs(self, nums: List[int]) -> int:
        d = defaultdict(list)

        for i in range(len(nums)):
            d[nums[i]].append(i)

        pairs = 0

        for n, idxs in d.items():
            if len(idxs) > 1:
              pairs += len(idxs) * (len(idxs) - 1) // 2

        return pairs
