
# AUTOGENERATED WITH https://github.com/tsecret/leetcode

# URL: https://leetcode.com/problems/merge-strings-alternately
# topics: two-pointers, string


class Solution:
    def mergeAlternately(self, word1: str, word2: str) -> str:
        l = 0
        r = 0

        ans = []

        while l < len(word1) or r < len(word2):

          if l < len(word1):
            ans.append(word1[l])

          if r < len(word2):
            ans.append(word2[r])

          l += 1
          r += 1

        return "".join(ans)
