
# AUTOGENERATED WITH https://github.com/tsecret/leetcode

# URL: https://leetcode.com/problems/two-sum
# topics: array, hash-table

from typing import List

class Solution:
    def twoSum(self, nums: List[int], target: int) -> List[int]:
        d = {}

        for i in range(len(nums)):
          if nums[i] not in d:
            d[nums[i]] = []

          d[nums[i]].append(i)

        for i in range(len(nums)):
          print(nums[i], 'need', target-nums[i])
          if (target - nums[i]) in d:
            for j in d[target-nums[i]]:
               if i == j:
                  continue
               return [i, j]

        return None
