
# AUTOGENERATED WITH https://github.com/tsecret/leetcode

# URL: https://leetcode.com/problems/contains-duplicate-ii
# topics: array, hash-table, sliding-window


from typing import List
from collections import defaultdict

class Solution:
    def containsNearbyDuplicate(self, nums: List[int], k: int) -> bool:
        d = defaultdict(list)


        for i in range(len(nums)):
            d[nums[i]].append(i)

        print(d)

        for v in d.values():
            if len(v) >= 2:

              for i in range(len(v)-1):
                if abs(v[i+1] - v[i]) <= k:
                   return True

        return False
